import {useState} from 'react'
import Head from 'next/head'
import {supabase} from '../../lib/supabase'
import VICHeader from '../../components/VICHeader'
export default function StaffSetup(){
 const [text,setText]=useState(''),[plan,setPlan]=useState(null),[confirmation,setConfirmation]=useState(''),[results,setResults]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[approved,setApproved]=useState(false)
 async function request(mode){
  setBusy(true);setError('')
  try{
   const rows=JSON.parse(text),{data:{session}}=await supabase.auth.getSession()
   if(!session)throw new Error('Log in with your school administrator account first.')
   const r=await fetch('/api/admin/create-staff',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${session.access_token}`},body:JSON.stringify({rows,mode,...(mode==='apply'?{confirmation}:{})})}),d=await r.json()
   if(!r.ok)throw new Error(d.error||'Could not complete setup.')
   if(mode==='preview'){setPlan(d.plan);setConfirmation(d.confirmation);setResults(null);setApproved(false)}
   else{setResults(d.results);setPlan(null);setConfirmation('');setApproved(false)}
  }catch(e){setError(e.message)}finally{setBusy(false)}
 }
 function update(value){setText(value);setPlan(null);setConfirmation('');setResults(null);setApproved(false)}
 async function upload(e){try{const file=e.target.files?.[0];if(file){if(file.size>32000)throw new Error('Choose a file under 32 KB.');update(await file.text())}}catch(e){setError(e.message)}}
 return <main><Head><title>Staff account setup | Ask VIC</title></Head><VICHeader currentPath="/admin/staff-setup"/><h1>Set up your staff</h1><p>Review staff accounts before creating or linking them. This gives teacher tools and Lesson Designer access. Administrator rights and student rosters are unchanged.</p><nav><a href="/login?next=/admin/staff-setup">Administrator login</a> · <a href="/admin/accounts">Manage accounts</a> · <a href="/admin/classrooms">Manage classrooms</a></nav><section><label>Upload your prepared staff file<input type="file" accept="application/json,.json" onChange={upload} disabled={busy}/></label><details><summary>Or paste staff details</summary><label>Staff JSON<textarea value={text} disabled={busy} onChange={e=>update(e.target.value)} placeholder={'[{"name":"Teacher name","email":"teacher@example.com"}]'}/></label></details><button disabled={busy||!text.trim()} onClick={()=>request('preview')}>{busy?'Working…':'Review staff setup'}</button>{error&&<p role="alert" className="error">{error}</p>}{plan&&<><h2>Review these accounts</h2><ul>{plan.map(r=><li key={r.email}><strong>{r.name}</strong><br/>{r.email}<br/>{r.status} — Teacher tools + Lesson Designer</li>)}</ul><p>Existing passwords stay as they are. New staff use their email login link or code to verify their address and sign in. No emails are sent by this setup.</p><label className="check"><input type="checkbox" checked={approved} onChange={e=>setApproved(e.target.checked)}/>I approve teacher-tool access for every person listed above.</label><button disabled={busy||!approved} onClick={()=>request('apply')}>Apply reviewed staff setup</button></>}{results&&<><h2>Setup results</h2><ul>{results.map(r=><li key={r.email}><strong>{r.name}: {r.status}</strong><br/>{r.email}{r.error&&<p className="error">{r.error}</p>}</li>)}</ul>{results.some(r=>r.status!=='Ready')?<p>Review setup again to safely finish the remaining accounts.</p>:<p>Staff accounts are ready. Each person can open <a href="/login">educator login</a> and request their own email link. Classroom assignments are managed separately.</p>}</>}</section><style jsx>{`main{max-width:900px;margin:auto;padding:24px}h1{margin-top:36px;font-size:36px}p{line-height:1.6}section{margin-top:24px;padding:28px;border:1px solid var(--vic-border);border-radius:16px;background:var(--vic-surface)}label{display:grid;gap:12px;margin:20px 0;font-weight:700}input,textarea{padding:12px}textarea{min-height:220px;width:100%;font-family:monospace}button{padding:14px 20px;border:0;border-radius:9px;background:var(--vic-primary);color:white;font-weight:800;cursor:pointer}button:disabled{opacity:.5;cursor:default}li{padding:14px 0;border-bottom:1px solid var(--vic-border);overflow-wrap:anywhere}.check{display:flex;align-items:center}.error{color:var(--vic-danger)}`}</style></main>
}
