import {useState} from 'react'
import {supabase} from '../lib/supabase'
export default function AddClassStudents({classId,className,onAdded}){
 const [q,setQ]=useState(''),[matches,setMatches]=useState([]),[selected,setSelected]=useState({}),[searched,setSearched]=useState(false),[canCreate,setCanCreate]=useState(false),[approximate,setApproximate]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('')
 async function request(body){const {data:{session}}=await supabase.auth.getSession();if(!session)throw new Error('Sign in again to manage your roster.');const r=await fetch('/api/teacher/enroll-students',{method:'POST',headers:{Authorization:`Bearer ${session.access_token}`,'Content-Type':'application/json'},body:JSON.stringify({classId,...body})});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||'Could not update the roster.');return data}
 async function search(e){e.preventDefault();setBusy(true);setError('');setNotice('');setSelected({});try{const d=await request({action:'search',q});setMatches(d.students);setCanCreate(d.canCreateAccount);setApproximate(d.approximate);setSearched(true)}catch(e){setError(e.message)}finally{setBusy(false)}}
 async function add(){setBusy(true);setError('');setNotice('');try{const d=await request({action:'add',studentIds:Object.keys(selected).filter(id=>selected[id]).map(Number)});await onAdded?.();setSelected({});setNotice(`${d.added} student${d.added===1?'':'s'} added to ${className}.${d.alreadyEnrolled?` ${d.alreadyEnrolled} already enrolled.`:''}`)}catch(e){setError(e.message)}finally{setBusy(false)}}
 const count=Object.values(selected).filter(Boolean).length
 return <details className="addStudents"><summary>Add students to this class</summary><p>Find existing student accounts by first name, last name, or username. Select the correct names and add them to <strong>{className}</strong>.</p><form onSubmit={search}><label>Find students<input required minLength={2} maxLength={100} value={q} disabled={busy} onChange={e=>{setQ(e.target.value);setSearched(false);setMatches([]);setSelected({})}} placeholder="For example: John Louis"/></label><button disabled={busy}>{busy?'Working…':'Find students'}</button></form>{error&&<p role="alert" className="error">{error}</p>}{approximate&&searched&&<p>These match the first and last names. Check the full name before adding.</p>}{searched&&!matches.length&&<p>No existing student account matched. {canCreate?<a href="/admin/accounts?create=student">Create one student account →</a>:'Ask your administrator to create the account first.'}</p>}{matches.length>0&&<><div className="matches">{matches.map(s=><label key={s.id}><input type="checkbox" disabled={busy} checked={!!selected[s.id]} onChange={e=>setSelected(current=>({...current,[s.id]:e.target.checked}))}/><span><strong>{s.name}</strong>{s.username&&<small>Username: {s.username}</small>}</span></label>)}</div><button type="button" className="primary" disabled={busy||!count} onClick={add}>Add {count} selected student{count===1?'':'s'} to this class</button></>}{notice&&<p role="status">{notice}</p>}<style jsx>{`.addStudents{margin:18px 0;padding:18px;border:1px solid var(--vic-border);border-radius:12px;background:var(--vic-surface)}summary{font-weight:800;color:var(--vic-primary);cursor:pointer}p{font-size:13px;line-height:1.6;color:var(--vic-text-secondary)}form{display:flex;gap:10px;align-items:end;flex-wrap:wrap}form label{display:grid;gap:7px;flex:1;min-width:200px;font-size:13px;font-weight:700}input:not([type=checkbox]){width:100%;border:1px solid var(--vic-border);border-radius:8px;padding:10px;font:inherit}button{border:1px solid var(--vic-border);border-radius:8px;padding:11px 14px;background:var(--vic-surface-muted);font-weight:750;cursor:pointer}.primary{background:var(--vic-primary);color:white}.matches{display:grid;gap:8px;margin:16px 0}.matches label{display:flex;align-items:center;gap:10px;padding:10px;background:var(--vic-surface-muted);border-radius:8px}small{display:block;font-size:12px;color:var(--vic-text-secondary);margin-top:4px}a{color:var(--vic-primary);font-weight:750}.error{color:var(--vic-danger)}button:disabled{opacity:.5;cursor:not-allowed}`}</style></details>
}
