import {useEffect,useState} from 'react'
import {supabase} from '../lib/supabase'

export default function FamilyUpdates(){
 const [items,setItems]=useState([]),[chosen,setChosen]=useState({}),[combined,setCombined]=useState(''),[loading,setLoading]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('')
 async function load(){setLoading(true);setError('');try{const {data:{session}}=await supabase.auth.getSession();if(!session)throw new Error('Sign in again to see your updates.');const response=await fetch('/api/educator/lesson-companion?collection=family',{headers:{Authorization:`Bearer ${session.access_token}`}});const data=await response.json();if(!response.ok)throw new Error(data.error||'Could not load family updates.');setItems(data.drafts);setChosen(previous=>Object.fromEntries(data.drafts.map(item=>[item.lesson_id,previous[item.lesson_id]??false])))}catch(e){setError(e.message)}finally{setLoading(false)}}
 useEffect(()=>{load()},[])
 function assemble(){const selected=items.filter(item=>chosen[item.lesson_id]);if(!selected.length){setError('Choose at least one saved update.');return}setCombined(`Hello families,\n\n${selected.map(item=>item.draft.replace(/^Family update:[^\n]*\n\n/i,'').replace(/\n\nThank you for learning with us!\s*$/i,'')).join('\n\n')}\n\nThank you for learning with us!`);setError('');setNotice('Combined draft ready. Edit it before copying or sharing.')}
 async function copy(){try{await navigator.clipboard.writeText(combined);setNotice('Copied for your review and school messaging tool.')}catch{setError('Select the text and copy it instead.')}}
 return <section className="familyShelf" aria-labelledby="familyShelfTitle"><div className="top"><div><p className="eyebrow">FAMILY COMMUNICATION</p><h2 id="familyShelfTitle">Saved family updates</h2></div><button type="button" onClick={load} disabled={loading}>{loading?'Loading…':'Show / refresh drafts'}</button></div><p>Make one update from a lesson, or choose several for a weekly message. Drafts stay saved with your lessons until you decide to copy and send them through your school’s usual channel.</p>{error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}{items.map(item=><label key={item.lesson_id}><input type="checkbox" checked={!!chosen[item.lesson_id]} onChange={e=>setChosen({...chosen,[item.lesson_id]:e.target.checked})}/><span><strong>{item.title}</strong><small>Saved {new Date(item.updated_at).toLocaleString()}</small></span><a href={`/educator?lesson=${encodeURIComponent(item.lesson_id)}#lesson-assistant`}>Edit ↗</a></label>)}{items.length>0&&<button type="button" onClick={assemble}>Combine selected updates</button>}{combined&&<div className="combined"><label htmlFor="familyCombined">Editable message to families</label><textarea id="familyCombined" rows="12" value={combined} onChange={e=>setCombined(e.target.value)}/><button type="button" onClick={copy}>Copy reviewed message</button><small>This combined message stays here while this page is open. Each lesson update remains saved in your account. Nothing is sent automatically.</small></div>}<style jsx>{`.familyShelf{border:1px solid var(--vic-border);border-radius:18px;padding:26px;background:var(--vic-surface);margin:20px 0}.top{display:flex;align-items:center;justify-content:space-between;gap:12px}.eyebrow{font-size:10px;letter-spacing:.1em;font-weight:800;color:var(--vic-primary)}h2{margin:5px 0;font-size:25px}p,small{font-size:13px;line-height:1.6;color:var(--vic-text-secondary)}button{border:1px solid var(--vic-primary);background:white;color:var(--vic-primary);padding:10px;border-radius:9px;font-weight:700;cursor:pointer}.familyShelf>label{display:flex;align-items:center;gap:12px;border-top:1px solid var(--vic-border-soft);padding:12px 0;font-size:13px}.familyShelf>label input{width:18px;height:18px}.familyShelf>label span{flex:1}.familyShelf>label small{display:block}.familyShelf a{color:var(--vic-primary)}.combined{margin-top:20px}.combined label{display:block;font-weight:700;font-size:13px}.combined textarea{display:block;width:100%;padding:12px;margin:8px 0;line-height:1.5}.combined small{display:block;margin-top:8px}@media(max-width:650px){.familyShelf{padding:20px}.top{align-items:flex-start;flex-direction:column}}`}</style></section>
}
