import {useEffect,useState} from 'react'
import {supabase} from '../lib/supabase'
import {lessonLink} from '../lib/educator-lessons.mjs'
import {COMPANION_TOOLS} from '../lib/lesson-companion.mjs'

export default function LessonCompanion({lessonId,onUseWithVic,canUseVic}){
 const [lesson,setLesson]=useState(null),[work,setWork]=useState({}),[kind,setKind]=useState('prep'),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[dirty,setDirty]=useState({})
 async function request(body){
  const {data:{session}}=await supabase.auth.getSession()
  if(!session)throw new Error('Please sign in again to use this lesson.')
  const r=await fetch(body?'/api/educator/lesson-companion':`/api/educator/lesson-companion?lessonId=${encodeURIComponent(lessonId)}`,{method:body?'POST':'GET',headers:{Authorization:`Bearer ${session.access_token}`,...(body?{'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify({lessonId,...body})}:{})})
  const d=await r.json().catch(()=>({}))
  if(!r.ok)throw new Error(d.error||'Could not open this lesson assistant.')
  return d
 }
 useEffect(()=>{let active=true;setLoading(true);setLesson(null);setWork({});setDirty({});setError('');setMessage('');request().then(d=>{if(active){setLesson(d.lesson);setWork(Object.fromEntries(d.work.map(item=>[item.kind,item])))}}).catch(e=>{if(active)setError(e.message)}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[lessonId])
 const current=work[kind]||{notes:'',draft:''}
 function update(field,value){setWork(w=>({...w,[kind]:{...(w[kind]||{notes:'',draft:''}),[field]:value}}));setDirty(d=>({...d,[kind]:true}));setMessage('')}
 async function mutate(action){setBusy(true);setError('');setMessage('');try{const d=await request({action,kind,notes:current.notes,draft:current.draft});setWork(w=>({...w,[kind]:d.work}));setDirty(dirty=>({...dirty,[kind]:false}));setMessage(action==='generate'?'Draft saved. Edit it before using.':'Your edits are saved.')}catch(e){setError(e.message)}finally{setBusy(false)}}
 async function copy(){try{await navigator.clipboard.writeText(current.draft);setMessage('Copied. Review before sharing.')}catch{setError('Copy is unavailable. Select the text instead.')}}
 function download(){const url=URL.createObjectURL(new Blob([current.draft],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`VIC-${kind}-${lessonId.slice(0,8)}.txt`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
 function printDraft(){const page=window.open('','_blank');if(!page){setError('Print was blocked. Download the draft instead.');return}page.opener=null;page.document.write('<!doctype html><html><head><title>VIC teacher draft</title><style>body{font:12pt/1.5 Arial,sans-serif;max-width:750px;margin:40px auto;padding:0 20px}pre{white-space:pre-wrap;font:inherit}</style></head><body></body></html>');page.document.close();const h=page.document.createElement('h1');h.textContent=COMPANION_TOOLS[kind].title;const pre=page.document.createElement('pre');pre.textContent=current.draft;page.document.body.append(h,pre);page.focus();page.print()}
 function reviseLesson(){try{sessionStorage.setItem(`vic-lesson-revision:${lessonId}`,`Use this reviewed next-day adjustment: ${current.draft}`.slice(0,1000))}catch{setError('Could not transfer the adjustment. Copy it and paste it into the lesson revision box.');return}window.location.href=lessonLink(lessonId)}
 return <section className="companion" id="lesson-assistant" aria-busy={loading||busy} aria-labelledby="companion-title">
  <p className="eyebrow">LESSON-BASED TEACHER ASSISTANT</p><h2 id="companion-title">{lesson?`Work from “${lesson.title}”`:'Your lesson assistant'}</h2>
  {loading?<p role="status">Opening saved lesson…</p>:error&&!lesson?<p role="alert">{error}</p>:<>
   <p>The lesson is already here. Choose what you need; add only details VIC could not know. Every draft is private and editable.</p>
   <div className="actions"><a href={`${lessonLink(lessonId)}#worksheet`}>Create or edit printable worksheet and answer key ↗</a>{lesson?.hasWorksheet&&<span>Worksheet saved with this lesson</span>}</div>
   <nav aria-label="Lesson assistant tools">{Object.entries(COMPANION_TOOLS).filter(([key])=>key!=='vic').map(([key,tool])=><button type="button" key={key} aria-pressed={kind===key} onClick={()=>{setKind(key);setError('');setMessage('')}}>{tool.label}{dirty[key]?' •':''}</button>)}</nav>
   {canUseVic&&<div className="actions"><button type="button" className="primary" disabled={busy||!lesson?.vicText} onClick={()=>onUseWithVic({title:lesson.title,text:lesson.vicText})}>Send standard &amp; objectives to VIC classroom ↓</button>{lesson?.vicError&&<small>{lesson.vicError}</small>}</div>}
   {message&&<p className="notice" role="status">{message}</p>}{error&&<p className="error" role="alert">{error}</p>}
   <div className="grid"><div><h3>{COMPANION_TOOLS[kind].title}</h3><label>{kind==='next'?'What happened when you taught it? (optional)':kind==='family'?'What has happened in class? (optional)':'Anything VIC should consider? (optional)'}<textarea rows="6" value={current.notes} disabled={busy} maxLength="1500" onChange={e=>update('notes',e.target.value)} placeholder={kind==='next'?'The class understood the model but needed more practice with…':kind==='family'?'We practiced this week; families asked about…':'Available materials, time, or a change to the plan…'}/></label><button type="button" className="primary" disabled={busy} onClick={()=>mutate('generate')}>{busy?'Working…':current.draft?'Create a fresh draft':'Create draft from lesson'}</button><small>{kind==='family'?'Saved in your Family Updates collection for a daily or weekly message.':'A fresh draft replaces this tool’s previous draft after it succeeds.'} Leave out student names and confidential details.</small></div>
    <div><label>Editable draft<textarea rows="15" value={current.draft} disabled={busy} maxLength="12000" onChange={e=>update('draft',e.target.value)} placeholder="Your draft will appear here. Review and edit it before using."/></label><div className="actions"><button type="button" className="primary" disabled={busy||!dirty[kind]} onClick={()=>mutate('save')}>Save my edits</button><button type="button" disabled={busy||!current.draft} onClick={copy}>Copy</button><button type="button" disabled={busy||!current.draft} onClick={download}>Download text</button><button type="button" disabled={busy||!current.draft} onClick={printDraft}>Print / PDF</button></div>{kind==='next'&&<button type="button" className="primary" disabled={busy||!current.draft||dirty.next} onClick={reviseLesson}>Open lesson with this revision ↓</button>}<small>{dirty[kind]?'Unsaved changes.':current.updated_at?`Saved ${new Date(current.updated_at).toLocaleString()}`:'Nothing has been saved yet.'} Nothing is sent or assigned automatically.</small></div></div>
  </>}
  <style jsx>{`.companion{border:1px solid var(--vic-border);border-radius:18px;padding:26px;background:var(--vic-surface);margin:22px 0 30px;scroll-margin-top:18px}.eyebrow{font-size:10px;letter-spacing:.1em;font-weight:800;color:var(--vic-primary)}h2{font-size:27px;margin:8px 0}h3{margin:0 0 18px}p,small{line-height:1.6;color:var(--vic-text-secondary)}nav,.actions{display:flex;gap:8px;flex-wrap:wrap;align-items:center;margin:16px 0}nav button,.actions button,.primary{border:1px solid var(--vic-border);background:white;border-radius:9px;padding:10px 13px;cursor:pointer;color:var(--vic-text-primary);font-weight:700}nav button[aria-pressed=true],.primary{background:var(--vic-primary);border-color:var(--vic-primary);color:white}button:disabled{opacity:.55;cursor:not-allowed}.actions a{color:var(--vic-primary);font-weight:700;font-size:13px}.actions span,small{font-size:12px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:20px}label{display:block;font-size:13px;font-weight:700}textarea{display:block;width:100%;margin:8px 0 14px;padding:12px;border:1px solid var(--vic-border);border-radius:8px;resize:vertical;font:inherit;line-height:1.5}.notice,.error{padding:10px;border-radius:8px}.notice{background:var(--vic-success-soft)}.error{background:var(--vic-danger-soft)}@media(max-width:720px){.companion{padding:20px}.grid{grid-template-columns:1fr}}@media print{.companion nav,.companion button,.companion .grid>div:first-child,.companion .actions,.companion>p,.companion small{display:none!important}.companion{border:0;padding:0;margin:0}.companion textarea{border:0;min-height:70vh;font-size:12pt}}`}</style>
 </section>
}
