import {useEffect,useState} from 'react'
import {supabase} from '../lib/supabase'
import {lessonLink,validLessonId} from '../lib/educator-lessons.mjs'
import {draftKey,lessonLibraryRequest,persistLesson} from '../lib/lesson-library-client'
import LessonCompanion from './LessonCompanion'

export default function MyEducatorLessons({canUseVic}){
 const [lessons,setLessons]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[more,setMore]=useState(false),[filter,setFilter]=useState(''),[selected,setSelected]=useState('')
 async function load(append=false){setLoading(true);setError('');try{
  if(!append){const {data:{session}}=await supabase.auth.getSession();if(session){let cached;try{cached=JSON.parse(localStorage.getItem(draftKey(session.user.id))||'null')}catch{}if(cached?.plan&&cached.input&&(!cached.savedLessonId||cached._pendingSave)){cached={...cached,savedLessonId:cached.savedLessonId||crypto.randomUUID()};localStorage.setItem(draftKey(session.user.id),JSON.stringify(cached));await persistLesson(cached,session.user.id)}}}
  const d=await lessonLibraryRequest(`?offset=${append?lessons.length:0}`);setLessons(append?[...lessons,...d.lessons]:d.lessons);setMore(d.hasMore)
 }catch(e){setError(e.message)}finally{setLoading(false)}}
 useEffect(()=>{const id=new URLSearchParams(window.location.search).get('lesson');if(validLessonId(id))setSelected(id);load()},[])
 function choose(id){setSelected(id);window.history.replaceState(null,'',`/educator?lesson=${encodeURIComponent(id)}#lesson-assistant`);setTimeout(()=>document.getElementById('lesson-assistant')?.scrollIntoView({behavior:'smooth'}),50)}
 const shown=lessons.filter(l=>`${l.title} ${l.subject} ${l.grade}`.toLowerCase().includes(filter.toLowerCase()))
 return <><section className="library" aria-labelledby="my-lessons-title"><div className="heading"><div><p>YOUR LESSON LIBRARY</p><h2 id="my-lessons-title">My Lessons</h2></div><a className="newLesson" href="/lessonplan?new=1">＋ Create a new lesson</a></div>
  <p className="help">Your saved ELA, math, science, and other lessons stay here. Open a plan to edit it, or let the assistant prepare materials from it.</p>
  {lessons[0]&&<a className="recent" href={lessonLink(lessons[0].id)}><span>MOST RECENTLY UPDATED</span><strong>{lessons[0].title}</strong><span>Open lesson →</span></a>}
  {error&&<p role="alert">{error} <button onClick={()=>load()}>Retry</button></p>}
  {lessons.length>0&&<label>Find a lesson<input value={filter} onChange={e=>setFilter(e.target.value)} placeholder="Search by title, subject, or grade"/></label>}
  {loading&&<p role="status">Loading your lessons…</p>}{!loading&&!error&&!lessons.length&&<p>Your saved lessons will appear here after you create your first plan.</p>}
  <div className="lessonList">{shown.map(l=><div className="lessonRow" key={l.id}><a href={lessonLink(l.id)}><h3>{l.title}</h3><p>{l.subject==='reading'?'Reading / ELA':l.subject} · Grade {l.grade} · Updated {new Date(l.updated_at).toLocaleDateString()}</p></a><div className="lessonButtons">{canUseVic&&<a className="assignLink" href={`/assignlesson?lessonId=${encodeURIComponent(l.id)}`}>Assign in VIC →</a>}<button type="button" onClick={()=>choose(l.id)}>Prepare with assistant →</button></div></div>)}</div>
  {!loading&&lessons.length>0&&!shown.length&&<p>No matching lessons in the loaded results.</p>}{more&&<button disabled={loading} onClick={()=>load(true)}>Load more lessons</button>}
  <style jsx>{`.library{padding:26px;border:1px solid var(--vic-border);border-radius:18px;background:var(--vic-surface);margin:0 0 18px}.heading{display:flex;align-items:center;justify-content:space-between;gap:16px}.heading p,.recent>span:first-child{font-size:9px;letter-spacing:.1em;color:var(--vic-primary);font-weight:800;margin:0 0 10px}h2{font-size:28px;margin:0}.newLesson{background:var(--vic-primary);color:white;border-radius:10px;padding:12px 17px;text-decoration:none;font-size:13px;font-weight:750}.help{font-size:13px;line-height:1.7;color:var(--vic-text-secondary)}.recent{display:grid;gap:8px;background:#edf0e4;border-radius:12px;padding:20px;color:var(--vic-text-primary);text-decoration:none;margin:22px 0}.recent span{font-size:12px}.recent strong{font-size:20px}.recent>span:first-child{margin:0}label{display:block;font-size:12px;font-weight:700}input{display:block;width:100%;padding:12px;border:1px solid var(--vic-border);border-radius:9px;margin:8px 0 15px}.lessonList{display:grid;gap:10px}.lessonRow{display:flex;align-items:center;justify-content:space-between;gap:15px;padding:16px;border:1px solid var(--vic-border-soft);border-radius:10px}.lessonButtons{display:flex;gap:8px;flex-wrap:wrap}.lessonRow .assignLink{flex:none;border-radius:8px;background:var(--vic-primary);color:white;padding:10px 13px;font-size:13px;font-weight:750}.lessonRow a{text-decoration:none;color:var(--vic-text-primary);flex:1}.lessonRow button,button{padding:9px 13px;cursor:pointer;border:1px solid var(--vic-primary);color:var(--vic-primary);background:white;border-radius:8px;font-weight:700}.lessonRow h3{font-size:16px;margin:0}.lessonRow p{font-size:12px;color:var(--vic-text-secondary);margin:8px 0 0}@media(max-width:650px){.library{padding:20px}.heading,.lessonRow{align-items:flex-start;flex-direction:column}.recent strong{font-size:18px}}`}</style>
 </section>{selected&&<LessonCompanion key={selected} lessonId={selected} canUseVic={canUseVic}/>}</>
}
