import {useEffect,useState} from 'react'
import VICHeader from '../../components/VICHeader'
import {supabase} from '../../lib/supabase'
export default function Preferences(){
 const [session,setSession]=useState(null),[ready,setReady]=useState(false),[subscribed,setSubscribed]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState('')
 useEffect(()=>{let active=true;supabase.auth.getSession().then(async({data})=>{if(!active)return;setSession(data.session);if(data.session){const r=await fetch('/api/lessonplan/access',{headers:{Authorization:`Bearer ${data.session.access_token}`}});const d=await r.json();if(!r.ok)throw new Error(d.error);if(active)setSubscribed(d.newsletterConsent)}if(active)setReady(true)}).catch(()=>{if(active){setReady(true);setMessage('Could not load your preferences. Please reload this page.')}});return()=>{active=false}},[])
 async function unsubscribe(){setBusy(true);try{const r=await fetch('/api/lessonplan/access',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${session.access_token}`},body:JSON.stringify({unsubscribe:true})});const d=await r.json();if(!r.ok)throw new Error(d.error);setSubscribed(false);setMessage('You have unsubscribed. Your Lesson Designer access remains available.')}catch(e){setMessage(e.message)}finally{setBusy(false)}}
 return <main style={{maxWidth:1000,margin:'auto',padding:24}}><VICHeader currentPath="/lessonplan"/><section style={{maxWidth:650,margin:'40px auto'}}><h1>Email preferences</h1>{!ready?<p>Loading…</p>:!session?<p><a href="/login">Log in</a> to manage your email preferences, then return to this page.</p>:<><p>{session.user.email}</p><p>{subscribed?'You receive Dr. Rob Furman’s educator updates.':'You are not subscribed to marketing updates.'}</p>{subscribed&&<button disabled={busy} onClick={unsubscribe}>{busy?'Saving…':'Unsubscribe from marketing updates'}</button>}<p>Unsubscribing does not remove your Lesson Designer access.</p></>}{message&&<p role="status">{message}</p>}<p><a href="/lessonplan">Open Lesson Designer</a></p></section></main>
}
