import Head from 'next/head'
import { useState } from 'react'
import VICHeader from '../../components/VICHeader'
const SOURCES=[
 {name:'Florida',status:'Built-in K–8 reading/ELA and math',links:[['Browse official standards','https://www.cpalms.org/standards/FLStandardSearch.aspx'],['B.E.S.T. mathematics','https://www.fldoe.org/academics/standards/subject-areas/math-science/mathematics/'],['B.E.S.T. reading/ELA','https://www.fldoe.org/academics/standards/just-read-fl/']]},
 {name:'Pennsylvania',status:'Built-in K–8 reading/ELA and math',links:[['Browse and search SAS standards','https://www.pdesas.org/Standard/View'],['Download official standards','https://www.pdesas.org/Page?pageId=11']]},
 {name:'Texas',status:'Paste a standard to create your lesson today',links:[['Texas Essential Knowledge and Skills (TEKS)','https://tea.texas.gov/curriculum-and-instruction/texas-essential-knowledge-and-skills-teks']]},
 {name:'Maryland',status:'Paste a standard to create your lesson today',links:[['Content standards and frameworks','https://www.marylandpublicschools.org/about/Pages/DCIPL/index_FW.aspx'],['Revised mathematics standards','https://marylandpublicschools.org/about/pages/dcaa/math/revised-standards.aspx'],['Reading/ELA standards','https://marylandpublicschools.org/programs/Pages/ELA/MCCR.aspx']]}
]
export default function StandardsDirectory(){
 const [state,setState]=useState(''),[grade,setGrade]=useState(''),[subject,setSubject]=useState(''),[email,setEmail]=useState(''),[notify,setNotify]=useState(true),[prepared,setPrepared]=useState(false)
 function request(e){e.preventDefault();const body=`State: ${state}\nGrade or course: ${grade}\nSubject: ${subject}\nReply email: ${email}\nNotify me when coverage is available: ${notify?'Yes':'No'}\n\nPlease consider adding these standards to Ask VIC Lesson Designer.`;window.location.href=`mailto:drrobfurman@gmail.com?subject=${encodeURIComponent('Lesson Designer state standards request')}&body=${encodeURIComponent(body)}`;setPrepared(true)}
 return <><Head><title>Official State Standards & Requests | Ask VIC Lesson Designer</title><meta name="description" content="Find official Florida, Pennsylvania, Texas, and Maryland standards. Request more state coverage or paste a standard into Ask VIC Lesson Designer."/></Head><main className="sd-shell"><VICHeader currentPath="/lessonplan"/><a href="/lessonplan">← Back to Lesson Designer</a><header><span>ASK VIC · OFFICIAL SOURCES</span><h1>Find your standard.<br/>Bring it to your lesson.</h1><p>Florida and Pennsylvania K–8 reading/ELA and math are built in. For another state, subject, or grade, copy the official standard’s code and wording, then choose “Paste my own standard” in Lesson Designer.</p></header><div className="sd-cards">{SOURCES.map(s=><section key={s.name}><h2>{s.name}</h2><p>{s.status}</p><ul>{s.links.map(([name,url])=><li key={url}><a href={url} target="_blank" rel="noopener noreferrer">{name} ↗</a></li>)}</ul></section>)}</div><section className="sd-wide"><h2>Another state?</h2><p>Use the <a href="https://nces.ed.gov/ccd/ccseas.asp" target="_blank" rel="noopener noreferrer">National Center for Education Statistics state education agency directory ↗</a> to find your state department of education. Look for its curriculum or academic standards section. Confirm the grade, subject, and version required by your school.</p></section><section className="sd-wide"><h2>Don’t see your state or subject?</h2><p>Request it here. We’re adding coverage based on teacher requests. You can paste your standard and create a lesson today.</p><form onSubmit={request}><div className="sd-grid"><label>State<input required value={state} onChange={e=>setState(e.target.value)} maxLength="60"/></label><label>Grade or course<input required value={grade} onChange={e=>setGrade(e.target.value)} maxLength="60"/></label><label>Subject<input required value={subject} onChange={e=>setSubject(e.target.value)} maxLength="100"/></label><label>Your email<input type="email" required value={email} onChange={e=>setEmail(e.target.value)} maxLength="254"/></label></div><label className="sd-check"><input type="checkbox" checked={notify} onChange={e=>setNotify(e.target.checked)}/>Notify me when this coverage is available.</label><button>Prepare email request</button><small>This opens an email draft to Dr. Rob Furman. Send it from your email app to submit your request. No request is sent by this page.</small>{prepared&&<p role="status">Your email draft was prepared. If your email app did not open, send your state, grade/course, and subject to <a href="mailto:drrobfurman@gmail.com">drrobfurman@gmail.com</a>.</p>}</form></section><footer>Official-source links checked October 4, 2026. Ask VIC is an independent educator tool.</footer></main><style jsx>{`
.sd-shell{max-width:1150px;margin:auto;padding:22px}.sd-shell>a{display:inline-block;margin-top:20px;font-size:14px}header{padding:40px 0 25px;max-width:780px}header span{font-size:12px;font-weight:800;letter-spacing:.12em;color:var(--vic-primary)}h1{font-size:clamp(34px,5vw,54px);line-height:1.1;letter-spacing:-.035em;margin:18px 0}p,li{line-height:1.7;color:var(--vic-text-secondary)}.sd-cards{display:grid;grid-template-columns:1fr 1fr;gap:20px}section{background:var(--vic-surface);border:1px solid var(--vic-border);border-radius:16px;padding:24px;box-shadow:var(--vic-shadow-soft)}h2{margin-top:0;font-size:22px}ul{padding-left:20px}li{margin-bottom:10px}.sd-wide{margin-top:22px}.sd-grid{display:grid;grid-template-columns:1fr 1fr;gap:15px}label{font-size:13px;font-weight:700}input:not([type=checkbox]){display:block;width:100%;padding:11px;border:1px solid var(--vic-border);border-radius:8px;margin-top:7px}.sd-check{display:flex;align-items:center;gap:8px;margin:20px 0}button{background:var(--vic-primary);color:white;border:0;border-radius:9px;padding:13px 18px;font-weight:750;cursor:pointer}small{display:block;line-height:1.6;max-width:700px;margin-top:12px;color:var(--vic-text-secondary)}footer{font-size:12px;margin:28px 0;color:var(--vic-text-secondary)}@media(max-width:650px){.sd-cards,.sd-grid{grid-template-columns:1fr}}
`}</style></>
}
